site_name: Amazon and Pinecone Documentation

nav:
  - Home: index.md
  - TestScale: 01-Test Scale.md
  - Concepts: 02-Concepts.md
  - Architecture: 03-Architecture.md
  - Create Index: 04-Create anIndex.md 
  - Data Modelling: data-modelling.mdc

theme:
  name: material
  